[package]
name = "hero-rest"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true}
serde_json = { workspace = true }
wit-bindgen = { workspace = true }
wasi = { workspace = true }
