#[cpu]
#name = "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"
#curve = [171.2,0.0354,36.89,-10.13]
[cpu]
name = "Apple M4 Pro"
curve = [30.508760345993128,0.0730308567638932,20.451103066868207,-5.08379885619235]


[[process]]
name = "superheroes"
up = "sleep 1"
down = "sleep 1"
redirect.to = "parent"
process.type = "docker"
process.containers = ["fights-db", "heroes-db", "villains-db", "locations-db", "wasmcloud", "wadm", "nats"]

startup_grace = "10s"

[[scenario]]
name = "200_microservice"
desc = "High load test. 200 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=200 -e K6_HOST=$K6_HOST:8004  k6/load.js --summary-export perf_data/k6_200.json"
iterations = 1
processes = ["superheroes"]

--log-output stderr

[[scenario]]
name = "100_microservice"
desc = "Load test. 100 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=100 -e K6_HOST=$K6_HOST:8004 k6/load.js --summary-export perf_data/k6_100.json"
iterations = 1
processes = ["superheroes"]

[[scenario]]
name = "1_microservice"
desc = "No load test. 1 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=1 -e K6_HOST=$K6_HOST:8004 k6/load.js  --summary-export perf_data/k6_1.json"
iterations = 1
processes = ["superheroes"]

[[scenario]]
name = "10_microservice"
desc = "Low load test, 10 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=10 -e K6_HOST=$K6_HOST:8004 k6/load.js --summary-export perf_data/k6_10.json"
iterations = 1
processes = ["superheroes"]


[[scenario]]
name = "200_component"
desc = "High load test. 200 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=200 -e K6_HOST=$K6_HOST:8005 k6/load.js --summary-export perf_data/k6_200.json"
iterations = 1
processes = ["superheroes"]

[[scenario]]
name = "100_component"
desc = "Load test. 100 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=100 -e K6_HOST=$K6_HOST:8005 k6/load.js --summary-export perf_data/k6_100.json"
iterations = 1
processes = ["superheroes"]

[[scenario]]
name = "1_component"
desc = "No load test. 1 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=1 -e K6_HOST=$K6_HOST:8005 k6/load.js  --summary-export perf_data/k6_1.json"
iterations = 1
processes = ["superheroes"]

[[scenario]]
name = "10_component"
desc = "Low load test, 10 r/s."
command = "k6 run --log-output stderr-e RAMPING_RATE=10 -e K6_HOST=$K6_HOST:8005 k6/load.js --summary-export perf_data/k6_10.json"
iterations = 1
processes = ["superheroes"]


[[observation]]
name = "microservice"
scenarios = ["1_microservice", "10_microservice", "100_microservice", "200_microservice"]

[[observation]]
name = "component"
scenarios = ["1_component", "10_component", "100_component", "200_component"]

[[observation]]
name = "microservice_high"
scenarios = ["100_microservice"]

[[observation]]
name = "component_high"
scenarios = ["100_component"]

