#[cpu]
#name = "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz"
#curve = [171.2,0.0354,36.89,-10.13]
[cpu]
name = "Apple M4 Pro"
curve = [30.508760345993128,0.0730308567638932,20.451103066868207,-5.08379885619235]


[[process]]
name = "superheroes"
up = "sleep 1"
down = "sleep 1"
redirect.to = "parent"
process.type = "docker"
process.containers = ["fights-db", "heroes-db", "villains-db", "locations-db", "wasmcloud"]

startup_grace = "10s"

[[scenario]]
name = "200"
desc = "High load test. 200 r/s."
command = "k6 run k6/load.js -e RAMPING_RATE=200 -e K6_HOST=http://localhost:8000 --summary-export k6_200.json"
iterations = 3
processes = ["superheroes"]

[[scenario]]
name = "100"
desc = "Load test. 100 r/s."
command = "k6 run -e RAMPING_RATE=100 -e K6_HOST=http://localhost:8000 k6/load.js --summary-export k6_100.json"
iterations = 3
processes = ["superheroes"]

[[scenario]]
name = "1"
desc = "No load test. 1 r/s."
command = "k6 run -e RAMPING_RATE=1 -e K6_HOST=http://localhost:8000 k6/load.js  --summary-export k6_1.json"
iterations = 3
processes = ["superheroes"]

[[scenario]]
name = "10"
desc = "Low load test, 10 r/s."
command = "k6 run -e RAMPING_RATE=10 -e K6_HOST=http://localhost:8000 k6/load.js --summary-export k6_10.json"
iterations = 3
processes = ["superheroes"]


[[observation]]
name = "1"
scenarios = ["none"]

[[observation]]
name = "low"
scenarios = ["low"]

[[observation]]
name = "high"
scenarios = ["high"]


[[observation]]
name = "max"
scenarios = ["max"]

[[observation]]
name = "all"
scenarios = ["1", "10", "100", "200"]


