[package]
name = "rest-heroes"
edition = "2021"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true}
serde_json = { workspace = true }
wit-bindgen = { workspace = true}
superhero-types = { path = "../../lib/superhero-types" }
