---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rest-heroes
  annotations:
    version: v0.0.2
    description: 'HTTP hello world demo in Rust, showing use of the server and client providers'
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: registry:5000/superheroes/rest-heroes:0.1.2
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            instances: 1
        # Establish a unidirectional link to the `httpclient` provider,
        # so the `http-component` (dog-fetching) component can make use of httpclient functionality
        # (i.e. making external web requests)
        - type: link
          properties:
            target:
              name: sqldb-postgres
              config:
                - name: default-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            source:
              config:
                - name: default-postgres
                  # properties:
                  #   connection_string: "postgres://superman:superman@heroes-db:5432/heroes_database"
                  #   pool_size: 10
                  #   max_lifetime: 30
                  #   max_idle_time: 10
                  #   min_idle_time: 5
                  #   max_open_conns: 100
                  #   max_idle_conns: 50

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
        ## To configure OTEL integration for this provider specifically, uncomment the lines below
        # config:
        #   - name: otel
        #     properties:
        #       otel_exporter_otlp_endpoint: "http://all-in-one:4318"
        #       otel_exporter_otlp_traces_endpoint: "http://traces-backend/v1/traces"
        #       otel_exporter_otlp_metrics_endpoint: "http://metrics-backend/v1/metrics"
        #       otel_exporter_otlp_logs_endpoint: "http://logs-backend/v1/logs"
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8000 for incoming requests
        #
        # Since the HTTP server calls the `http-component` component, we establish
        # a unidirectional link from this `httpserver` provider (the "source")
        # to the `http-component` component (the "target"), so the server can invoke
        # the component to handle an incoming HTTP request.
        - type: link
          properties:
            target:
              name: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source:
              config:
                - name: default-http
                  properties:
                    address: 0.0.0.0:8000

    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.10.0
        config:
          - name: default-postgres
            # properties:
            #   connection_string: "postgres://superman:superman@heroes-db:5432/heroes_database"
            #   pool_size: 10
            #   max_lifetime: 30
            #   max_idle_time: 10
            #   min_idle_time: 5
            #   max_open_conns: 100
            #   max_idle_conns: 50
