[package]
name = "rest-fights"
edition = "2021"
version = "0.1.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true}
serde_json = { workspace = true }
wasi = { workspace = true }
wit-bindgen = { workspace = true }
uuid = { workspace = true}