package hti:superheroes;

  // export wasi:http/incoming-handler@0.2.4;

interface types {
  
    record hero {
      id: s64,
      level: s32,
      name: string,
      other-name: option<string>,
      picture: string,
      powers: string,
    }
    record villain {
      id: s64,
      level: s32,
      name: string,
      other-name: option<string>,
      picture: string,
      powers: string,
    }
    record location {
      id: s64,
      name: string,
      description: string,
      picture: string,
      %type: location-type, // TODO use enum
    }

    variant location-type {
      city,
      planet,
      place,
      island,
      country,
      moon           
    }
}

world base {
  import wasmcloud:postgres/query@0.1.1-draft;
  import wasi:logging/logging@0.1.0-draft;
}


interface hero-repository {
  use types.{hero};
  get-hero: func(id: s64) -> option<hero>;
  get-random-hero: func() -> hero;
  get-all-heroes: func() -> list<hero>;  
}

interface villain-repository {
  use types.{villain};
  get-villain: func(id: s64) -> option<villain>;
  get-random-villain: func() -> villain;
  get-all-villains: func() -> list<villain>;  
}

interface location-repository {
  use types.{location};
  get-location: func(id: s64) -> option<location>;
  get-random-location: func() -> location;
  get-all-locations: func() -> list<location>;  
}


world hero-repository-world {
  include base;
  export hero-repository;
}

world villain-repository-world {
  include base;
  export villain-repository;
}

world location-repository-world {
  include base;
  export location-repository;
}

world hero-api-world {
  export wasi:http/incoming-handler@0.2.4;
  import wasi:logging/logging@0.1.0-draft;
  import hero-repository;
}

world villain-api-world {
  export wasi:http/incoming-handler@0.2.4;
  import wasi:logging/logging@0.1.0-draft;
  import villain-repository;
}

world location-api-world {
  export wasi:http/incoming-handler@0.2.4;
  import wasi:logging/logging@0.1.0-draft;
  import location-repository;
}



world superhero {
  include base;
  // include hero-repository-world;
  // include villain-repository-world;
  include hero-api-world;
  include villain-api-world;

}