---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: rest-locations
  annotations:
    version: v0.0.2
    description: HTTP hello world demo in Rust, showing use of the server and client
      providers
spec:
  components:
    - name: http-component
      type: component
      properties:
        image: registry:5000/superheroes/rest-locations:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: sqldb-postgres
              config:
                - name: locations-postgres
            namespace: wasmcloud
            package: postgres
            interfaces:
              - query
            source:
              config:
                - name: default-postgres
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.27.0
      traits:
        - type: link
          properties:
            target:
              name: http-component
            namespace: wasi
            package: http
            interfaces:
              - incoming-handler
            source:
              config:
                - name: rest-locations-http
                  properties:
                    address: 0.0.0.0:8003
    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.10.0
        config:
          - name: locations-postgres
