---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hero-repository
  annotations:
    version: v0.1.0
    description: 'HTTP repository querying superheroes'
spec:
  components:
    - name: hero-repository
      type: component
      properties:
        image: registry:5000/superheroes/hero-repository:0.1.0
      traits:
        - type: spreadscaler
          properties:
            instances: 1
        - type: link
          properties:
            target:
              name: sqldb-postgres
              config:
                - name: heroes-postgres
            namespace: wasmcloud
            package: postgres
            interfaces: [query]
            source:
              config:
                - name: heroes-postgres

    # Add a capability provider that enables HTTP access
    - name: sqldb-postgres
      type: capability
      properties:
        image: ghcr.io/wasmcloud/sqldb-postgres:0.10.0
        config:
          - name: heroes-postgres
