name: Test Docker on GitHub Actions

on:
  pull_request:
  push:
    branches: 
      - main
      - docker-compose-build
env:
  ARCHITECTURE: amd64
  K6_VERSION: "0.58.0"
  CARDAMON_VERSION: "0.2.18"

jobs:
  cardamon:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - name: Check location and dir
        run: |
          echo "Current directory: $(pwd)"
          echo "Current location: $(dirname $0)"
      # (Optional) If you need BuildKit / buildx features:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install curl
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
      - name: Install k6
        run: |
          echo "Installing k6 for architecture: $ARCHITECTURE" \
            && echo "URL: https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-${ARCHITECTURE}.tar.gz" \
            && curl -L https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-${ARCHITECTURE}.tar.gz -o k6.tgz \
            && tar xvfz k6.tgz \
            && mv k6-v${K6_VERSION}-linux-${ARCHITECTURE}/k6 /usr/local/bin/k6 \
            && chmod +x /usr/local/bin/k6 \
            && rm -rf k6.zip k6-v${K6_VERSION}-linux-${ARCHITECTURE} \
            && rm -rf k6-v${K6_VERSION}-linux-${ARCHITECTURE}
      - name: Install Cardamon
        run: |
          echo "Installing Cardamon for architecture: $ARCHITECTURE" \
            && curl -L https://github.com/flyaruu/cardamon-core/releases/download/v${CARDAMON_VERSION}/cardamon-x86_64-unknown-linux-gnu.tgz -o cardamon.tgz \
            && tar xvfz cardamon.tgz \
            && mv cardamon /usr/local/bin/cardamon \
            && rm -rf cardamon.tgz cardamon/

      - name: Build docker compose
        run: |
          ls -la
          echo "Current directory: ${PWD}"
          docker compose build
          docker compose pull
      - name: Run docker compose
        run: |
          docker compose up --force-recreate -d
      - name: Wait for services to start
        run: |
          sleep 10
      - name: Run k6 tests
        run: |
          docker compose exec builder cargo build --target wasm32-wasip2 --release
          docker compose exec builder pwd 
          docker compose exec builder ls -la 
          docker compose exec builder 'cd services && ./build.sh'
    #   - name: Cardamon All
    #     run: |
    #       export LOG_FILTER=info
    #       cardamon run all
    #   - name: Cardamon Stats
    #     run: |
    #       cardamon stats >stats.txt
    #       cat stats.txt

    #   - uses: actions/upload-artifact@v4
    #     with:
    #       name: cardamon-metrics
    #       path: |
    #         cardamon.db
    #         stats.txt
